clif_data_path: "Y:/DataStageData/CQODE DB Backbone/stable_2025_08/rclif/"
project_location: "Y:/DataStageData/Nick/CLIF/CLIF_PFvsSF_Performance"
file_type: "parquet"
site_lowercase: "UMN"
site_timezone: "America/Chicago"
