clif_data_path: "/projects/CLIF-analysis/critill_rclif_2_1/critill_rclif_2_1_tables"
project_location: "/projects/CLIF-analysis/clif_projects/CLIF_OxygenationMetrics/CLIF_PFvsSF_Performance"
file_type: "parquet"
site_lowercase: "hopkins"
site_timezone: "America/New_York"
